// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: departments.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateDepartment(ctx context.Context, name string) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment, name)
	var i Department
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteDepartment = `-- name: DeleteDepartment :execrows
DELETE FROM departments
WHERE id = $1
`

func (q *Queries) DeleteDepartment(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDepartment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDepartment = `-- name: GetDepartment :one
SELECT id, name, created_at FROM departments
WHERE id = $1
`

func (q *Queries) GetDepartment(ctx context.Context, id uuid.UUID) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartment, id)
	var i Department
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, name, created_at FROM departments
ORDER BY name
`

func (q *Queries) ListDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Department{}
	for rows.Next() {
		var i Department
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
