// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: departments.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (organization_id, code, name, parent_id, created_by, updated_by)
VALUES (
    $1::uuid,
    $2::text,
    $3::text,
    $4::uuid,
    $5::uuid,
    $5::uuid
)
RETURNING organization_id, id, code, name, parent_id, created_at, updated_at, created_by, updated_by
`

type CreateDepartmentParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	Code           *string    `json:"code"`
	Name           string     `json:"name"`
	ParentID       *uuid.UUID `json:"parent_id"`
	ActorID        *uuid.UUID `json:"actor_id"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment,
		arg.OrganizationID,
		arg.Code,
		arg.Name,
		arg.ParentID,
		arg.ActorID,
	)
	var i Department
	err := row.Scan(
		&i.OrganizationID,
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteDepartment = `-- name: DeleteDepartment :execrows
DELETE FROM departments
WHERE organization_id = $1::uuid
  AND id = $2::uuid
`

type DeleteDepartmentParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) DeleteDepartment(ctx context.Context, arg DeleteDepartmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDepartment, arg.OrganizationID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDepartment = `-- name: GetDepartment :one
SELECT organization_id, id, code, name, parent_id, created_at, updated_at, created_by, updated_by FROM departments
WHERE organization_id = $1::uuid
  AND id = $2::uuid
`

type GetDepartmentParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) GetDepartment(ctx context.Context, arg GetDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartment, arg.OrganizationID, arg.ID)
	var i Department
	err := row.Scan(
		&i.OrganizationID,
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many

SELECT organization_id, id, code, name, parent_id, created_at, updated_at, created_by, updated_by FROM departments
WHERE organization_id = $1::uuid
ORDER BY name
`

// Every query is scoped by organization_id. There are no unscoped variants to
// reach for by mistake.
func (q *Queries) ListDepartments(ctx context.Context, organizationID uuid.UUID) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Department{}
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.OrganizationID,
			&i.ID,
			&i.Code,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
