// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employees.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countEmployees = `-- name: CountEmployees :one
SELECT count(*) FROM employees
WHERE organization_id = $1::uuid
  AND ($2::uuid IS NULL OR department_id = $2::uuid)
  AND ($3::text IS NULL OR status = $3::text)
`

type CountEmployeesParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	DepartmentID   *uuid.UUID `json:"department_id"`
	Status         *string    `json:"status"`
}

func (q *Queries) CountEmployees(ctx context.Context, arg CountEmployeesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployees, arg.OrganizationID, arg.DepartmentID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (organization_id, department_id, full_name, email, title, status, hired_on)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::text,
    $4::text,
    $5::text,
    coalesce($6::text, 'active'),
    $7::date
)
RETURNING id, department_id, full_name, email, title, status, hired_on, created_at, updated_at, organization_id, designation_id, manager_id, phone, pan, aadhaar_last4, pf_number, esi_number, bank_account, bank_ifsc
`

type CreateEmployeeParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	DepartmentID   *uuid.UUID `json:"department_id"`
	FullName       string     `json:"full_name"`
	Email          string     `json:"email"`
	Title          *string    `json:"title"`
	Status         *string    `json:"status"`
	HiredOn        *time.Time `json:"hired_on"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.OrganizationID,
		arg.DepartmentID,
		arg.FullName,
		arg.Email,
		arg.Title,
		arg.Status,
		arg.HiredOn,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.FullName,
		&i.Email,
		&i.Title,
		&i.Status,
		&i.HiredOn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.DesignationID,
		&i.ManagerID,
		&i.Phone,
		&i.Pan,
		&i.AadhaarLast4,
		&i.PfNumber,
		&i.EsiNumber,
		&i.BankAccount,
		&i.BankIfsc,
	)
	return i, err
}

const deleteEmployee = `-- name: DeleteEmployee :execrows
DELETE FROM employees
WHERE organization_id = $1::uuid
  AND id = $2::uuid
`

type DeleteEmployeeParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) DeleteEmployee(ctx context.Context, arg DeleteEmployeeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEmployee, arg.OrganizationID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEmployee = `-- name: GetEmployee :one
SELECT id, department_id, full_name, email, title, status, hired_on, created_at, updated_at, organization_id, designation_id, manager_id, phone, pan, aadhaar_last4, pf_number, esi_number, bank_account, bank_ifsc FROM employees
WHERE organization_id = $1::uuid
  AND id = $2::uuid
`

type GetEmployeeParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) GetEmployee(ctx context.Context, arg GetEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployee, arg.OrganizationID, arg.ID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.FullName,
		&i.Email,
		&i.Title,
		&i.Status,
		&i.HiredOn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.DesignationID,
		&i.ManagerID,
		&i.Phone,
		&i.Pan,
		&i.AadhaarLast4,
		&i.PfNumber,
		&i.EsiNumber,
		&i.BankAccount,
		&i.BankIfsc,
	)
	return i, err
}

const listEmployees = `-- name: ListEmployees :many

SELECT id, department_id, full_name, email, title, status, hired_on, created_at, updated_at, organization_id, designation_id, manager_id, phone, pan, aadhaar_last4, pf_number, esi_number, bank_account, bank_ifsc FROM employees
WHERE organization_id = $1::uuid
  AND ($2::uuid IS NULL OR department_id = $2::uuid)
  AND ($3::text IS NULL OR status = $3::text)
ORDER BY full_name
LIMIT $5::int OFFSET $4::int
`

type ListEmployeesParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	DepartmentID   *uuid.UUID `json:"department_id"`
	Status         *string    `json:"status"`
	Offset         int32      `json:"offset"`
	Limit          int32      `json:"limit"`
}

// Every query is scoped by organization_id, including the writes: an UPDATE or
// DELETE that matched on id alone would reach across tenants.
func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployees,
		arg.OrganizationID,
		arg.DepartmentID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.DepartmentID,
			&i.FullName,
			&i.Email,
			&i.Title,
			&i.Status,
			&i.HiredOn,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
			&i.DesignationID,
			&i.ManagerID,
			&i.Phone,
			&i.Pan,
			&i.AadhaarLast4,
			&i.PfNumber,
			&i.EsiNumber,
			&i.BankAccount,
			&i.BankIfsc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees
SET department_id = coalesce($1::uuid, department_id),
    full_name     = coalesce($2::text, full_name),
    email         = coalesce($3::text, email),
    title         = coalesce($4::text, title),
    status        = coalesce($5::text, status),
    hired_on      = coalesce($6::date, hired_on),
    updated_at    = now()
WHERE organization_id = $7::uuid
  AND id = $8::uuid
RETURNING id, department_id, full_name, email, title, status, hired_on, created_at, updated_at, organization_id, designation_id, manager_id, phone, pan, aadhaar_last4, pf_number, esi_number, bank_account, bank_ifsc
`

type UpdateEmployeeParams struct {
	DepartmentID   *uuid.UUID `json:"department_id"`
	FullName       *string    `json:"full_name"`
	Email          *string    `json:"email"`
	Title          *string    `json:"title"`
	Status         *string    `json:"status"`
	HiredOn        *time.Time `json:"hired_on"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	ID             uuid.UUID  `json:"id"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.DepartmentID,
		arg.FullName,
		arg.Email,
		arg.Title,
		arg.Status,
		arg.HiredOn,
		arg.OrganizationID,
		arg.ID,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.FullName,
		&i.Email,
		&i.Title,
		&i.Status,
		&i.HiredOn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.DesignationID,
		&i.ManagerID,
		&i.Phone,
		&i.Pan,
		&i.AadhaarLast4,
		&i.PfNumber,
		&i.EsiNumber,
		&i.BankAccount,
		&i.BankIfsc,
	)
	return i, err
}
