// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employees.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countEmployees = `-- name: CountEmployees :one
SELECT count(*) FROM employees
WHERE organization_id = $1::uuid
  AND ($2::uuid IS NULL OR department_id = $2::uuid)
  AND ($3::employee_status IS NULL OR status = $3::employee_status)
`

type CountEmployeesParams struct {
	OrganizationID uuid.UUID       `json:"organization_id"`
	DepartmentID   *uuid.UUID      `json:"department_id"`
	Status         *EmployeeStatus `json:"status"`
}

func (q *Queries) CountEmployees(ctx context.Context, arg CountEmployeesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployees, arg.OrganizationID, arg.DepartmentID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (
    organization_id, employee_code, department_id, designation_id, full_name,
    email, phone, status, employment_type, hired_on, created_by, updated_by
)
VALUES (
    $1::uuid,
    $2::text,
    $3::uuid,
    $4::uuid,
    $5::text,
    $6::text,
    $7::text,
    coalesce($8::employee_status, 'probation'),
    coalesce($9::employment_type, 'full_time'),
    $10::date,
    $11::uuid,
    $11::uuid
)
RETURNING organization_id, id, employee_code, user_id, department_id, team_id, designation_id, manager_id, full_name, email, phone, gender, date_of_birth, status, employment_type, hired_on, confirmed_on, exited_on, pan, aadhaar_last4, uan, pf_number, esi_number, bank_account, bank_ifsc, address, created_at, updated_at, created_by, updated_by
`

type CreateEmployeeParams struct {
	OrganizationID uuid.UUID       `json:"organization_id"`
	EmployeeCode   string          `json:"employee_code"`
	DepartmentID   *uuid.UUID      `json:"department_id"`
	DesignationID  *uuid.UUID      `json:"designation_id"`
	FullName       string          `json:"full_name"`
	Email          string          `json:"email"`
	Phone          *string         `json:"phone"`
	Status         *EmployeeStatus `json:"status"`
	EmploymentType *EmploymentType `json:"employment_type"`
	HiredOn        *time.Time      `json:"hired_on"`
	ActorID        *uuid.UUID      `json:"actor_id"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.OrganizationID,
		arg.EmployeeCode,
		arg.DepartmentID,
		arg.DesignationID,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.Status,
		arg.EmploymentType,
		arg.HiredOn,
		arg.ActorID,
	)
	var i Employee
	err := row.Scan(
		&i.OrganizationID,
		&i.ID,
		&i.EmployeeCode,
		&i.UserID,
		&i.DepartmentID,
		&i.TeamID,
		&i.DesignationID,
		&i.ManagerID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Gender,
		&i.DateOfBirth,
		&i.Status,
		&i.EmploymentType,
		&i.HiredOn,
		&i.ConfirmedOn,
		&i.ExitedOn,
		&i.Pan,
		&i.AadhaarLast4,
		&i.Uan,
		&i.PfNumber,
		&i.EsiNumber,
		&i.BankAccount,
		&i.BankIfsc,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteEmployee = `-- name: DeleteEmployee :execrows
DELETE FROM employees
WHERE organization_id = $1::uuid
  AND id = $2::uuid
`

type DeleteEmployeeParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) DeleteEmployee(ctx context.Context, arg DeleteEmployeeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEmployee, arg.OrganizationID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEmployee = `-- name: GetEmployee :one
SELECT organization_id, id, employee_code, user_id, department_id, team_id, designation_id, manager_id, full_name, email, phone, gender, date_of_birth, status, employment_type, hired_on, confirmed_on, exited_on, pan, aadhaar_last4, uan, pf_number, esi_number, bank_account, bank_ifsc, address, created_at, updated_at, created_by, updated_by FROM employees
WHERE organization_id = $1::uuid
  AND id = $2::uuid
`

type GetEmployeeParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) GetEmployee(ctx context.Context, arg GetEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployee, arg.OrganizationID, arg.ID)
	var i Employee
	err := row.Scan(
		&i.OrganizationID,
		&i.ID,
		&i.EmployeeCode,
		&i.UserID,
		&i.DepartmentID,
		&i.TeamID,
		&i.DesignationID,
		&i.ManagerID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Gender,
		&i.DateOfBirth,
		&i.Status,
		&i.EmploymentType,
		&i.HiredOn,
		&i.ConfirmedOn,
		&i.ExitedOn,
		&i.Pan,
		&i.AadhaarLast4,
		&i.Uan,
		&i.PfNumber,
		&i.EsiNumber,
		&i.BankAccount,
		&i.BankIfsc,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listEmployees = `-- name: ListEmployees :many

SELECT organization_id, id, employee_code, user_id, department_id, team_id, designation_id, manager_id, full_name, email, phone, gender, date_of_birth, status, employment_type, hired_on, confirmed_on, exited_on, pan, aadhaar_last4, uan, pf_number, esi_number, bank_account, bank_ifsc, address, created_at, updated_at, created_by, updated_by FROM employees
WHERE organization_id = $1::uuid
  AND ($2::uuid IS NULL OR department_id = $2::uuid)
  AND ($3::employee_status IS NULL OR status = $3::employee_status)
ORDER BY full_name
LIMIT $5::int OFFSET $4::int
`

type ListEmployeesParams struct {
	OrganizationID uuid.UUID       `json:"organization_id"`
	DepartmentID   *uuid.UUID      `json:"department_id"`
	Status         *EmployeeStatus `json:"status"`
	Offset         int32           `json:"offset"`
	Limit          int32           `json:"limit"`
}

// Every query is scoped by organization_id, writes included: an UPDATE or
// DELETE matching on id alone would reach across tenants.
func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployees,
		arg.OrganizationID,
		arg.DepartmentID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.OrganizationID,
			&i.ID,
			&i.EmployeeCode,
			&i.UserID,
			&i.DepartmentID,
			&i.TeamID,
			&i.DesignationID,
			&i.ManagerID,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.Gender,
			&i.DateOfBirth,
			&i.Status,
			&i.EmploymentType,
			&i.HiredOn,
			&i.ConfirmedOn,
			&i.ExitedOn,
			&i.Pan,
			&i.AadhaarLast4,
			&i.Uan,
			&i.PfNumber,
			&i.EsiNumber,
			&i.BankAccount,
			&i.BankIfsc,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees
SET department_id   = coalesce($1::uuid, department_id),
    designation_id  = coalesce($2::uuid, designation_id),
    full_name       = coalesce($3::text, full_name),
    email           = coalesce($4::text, email),
    phone           = coalesce($5::text, phone),
    status          = coalesce($6::employee_status, status),
    employment_type = coalesce($7::employment_type, employment_type),
    hired_on        = coalesce($8::date, hired_on),
    updated_at      = now(),
    updated_by      = coalesce($9::uuid, updated_by)
WHERE organization_id = $10::uuid
  AND id = $11::uuid
RETURNING organization_id, id, employee_code, user_id, department_id, team_id, designation_id, manager_id, full_name, email, phone, gender, date_of_birth, status, employment_type, hired_on, confirmed_on, exited_on, pan, aadhaar_last4, uan, pf_number, esi_number, bank_account, bank_ifsc, address, created_at, updated_at, created_by, updated_by
`

type UpdateEmployeeParams struct {
	DepartmentID   *uuid.UUID      `json:"department_id"`
	DesignationID  *uuid.UUID      `json:"designation_id"`
	FullName       *string         `json:"full_name"`
	Email          *string         `json:"email"`
	Phone          *string         `json:"phone"`
	Status         *EmployeeStatus `json:"status"`
	EmploymentType *EmploymentType `json:"employment_type"`
	HiredOn        *time.Time      `json:"hired_on"`
	ActorID        *uuid.UUID      `json:"actor_id"`
	OrganizationID uuid.UUID       `json:"organization_id"`
	ID             uuid.UUID       `json:"id"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.DepartmentID,
		arg.DesignationID,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.Status,
		arg.EmploymentType,
		arg.HiredOn,
		arg.ActorID,
		arg.OrganizationID,
		arg.ID,
	)
	var i Employee
	err := row.Scan(
		&i.OrganizationID,
		&i.ID,
		&i.EmployeeCode,
		&i.UserID,
		&i.DepartmentID,
		&i.TeamID,
		&i.DesignationID,
		&i.ManagerID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Gender,
		&i.DateOfBirth,
		&i.Status,
		&i.EmploymentType,
		&i.HiredOn,
		&i.ConfirmedOn,
		&i.ExitedOn,
		&i.Pan,
		&i.AadhaarLast4,
		&i.Uan,
		&i.PfNumber,
		&i.EsiNumber,
		&i.BankAccount,
		&i.BankIfsc,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
