// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Department struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Employee struct {
	ID           uuid.UUID  `json:"id"`
	DepartmentID *uuid.UUID `json:"department_id"`
	FullName     string     `json:"full_name"`
	Email        string     `json:"email"`
	Title        *string    `json:"title"`
	Status       string     `json:"status"`
	HiredOn      *time.Time `json:"hired_on"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}
