// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, slug)
VALUES ($1::text, $2::text)
RETURNING id, name, slug, status, created_at, updated_at, legal_name, gstin, pan, state_code, address, phone, email
`

type CreateOrganizationParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LegalName,
		&i.Gstin,
		&i.Pan,
		&i.StateCode,
		&i.Address,
		&i.Phone,
		&i.Email,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, slug, status, created_at, updated_at, legal_name, gstin, pan, state_code, address, phone, email FROM organizations
WHERE id = $1::uuid
`

func (q *Queries) GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LegalName,
		&i.Gstin,
		&i.Pan,
		&i.StateCode,
		&i.Address,
		&i.Phone,
		&i.Email,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, status, created_at, updated_at, legal_name, gstin, pan, state_code, address, phone, email FROM organizations
WHERE lower(slug) = lower($1::text)
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LegalName,
		&i.Gstin,
		&i.Pan,
		&i.StateCode,
		&i.Address,
		&i.Phone,
		&i.Email,
	)
	return i, err
}

const listOrganizations = `-- name: ListOrganizations :many

SELECT id, name, slug, status, created_at, updated_at, legal_name, gstin, pan, state_code, address, phone, email FROM organizations
ORDER BY name
`

// Organisations are the tenant root, so these are the only queries in the
// codebase not scoped by organization_id. The /platform portal owns them; no
// HTTP route reaches them yet.
func (q *Queries) ListOrganizations(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LegalName,
			&i.Gstin,
			&i.Pan,
			&i.StateCode,
			&i.Address,
			&i.Phone,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganizationStatus = `-- name: UpdateOrganizationStatus :one
UPDATE organizations
SET status = $1::text,
    updated_at = now()
WHERE id = $2::uuid
RETURNING id, name, slug, status, created_at, updated_at, legal_name, gstin, pan, state_code, address, phone, email
`

type UpdateOrganizationStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateOrganizationStatus(ctx context.Context, arg UpdateOrganizationStatusParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganizationStatus, arg.Status, arg.ID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LegalName,
		&i.Gstin,
		&i.Pan,
		&i.StateCode,
		&i.Address,
		&i.Phone,
		&i.Email,
	)
	return i, err
}
